[bans]
# Forbid multiple versions of same dependency (with some exceptions)
multiple-versions = "deny"
# We should slways specify version ranges
wildcards = "deny"
# We specify features explicitly to avoid bloat
workspace-default-features = "deny"
# Avoid adding dependencies to this list as this slows down compilation.
skip-tree = [
    # TODO: Likely an issue in ahash dependency tree
    "getrandom",
    "wasi",
]
# Find another ways to avoid duplication
deny = [{ name = "openssl" }]


[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]
private = { ignore = true }


[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-org = { github = [] }


[advisories]
yanked = "deny"
ignore = [
    # paste is unmaintained (via parquet)
    # See: https://rustsec.org/advisories/RUSTSEC-2024-0436
    "RUSTSEC-2024-0436",
]
