name: build
on:
  push:
    paths-ignore:
      - "**.md"
  # manual trigger
  workflow_dispatch: {}
env:
  RUST_BACKTRACE: "1"
jobs:
  check_fmt:
    name: Check / Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
        with:
          toolchain: stable
          components: rustfmt
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  test_linux:
    name: Test / Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo test --verbose
